// DummyData.jsx
const matches = [
  {
    match_id: "match_123",
    tournament_name: "Midwest Regional",
    best_of: 3,
    rules: "First to 11 (win by 2)",
    winning: "Team Alpha leads 1–0",
    winner_team_id: null,
    games: [
      {
        number: 1,
        status: "final",
        t1_name: "Team Alpha",
        t1_score: 11,
        t1_logo: "/logos/alpha.png",
        t1_players: ["Ryan Smith", "Dodo Kong"],
        t2_name: "Team Beta",
        t2_score: 8,
        t2_logo: "/logos/beta.png",
        t2_players: ["Ethan Mahony", "Mary Layne Holloway"],
      },
      {
        number: 2,
        status: "in_progress",
        t1_name: "Team Alpha",
        t1_score: 7,
        t1_logo: "/logos/alpha.png",
        t1_players: ["Ryan Smith", "Dodo Kong"],
        t2_name: "Team Beta",
        t2_score: 6,
        t2_logo: "/logos/beta.png",
        t2_players: ["Ethan Mahony", "Mary Layne Holloway"],
      },
      {
        number: 3,
        status: "scheduled",
        t1_name: "Team Alpha",
        t1_score: 0,
        t1_logo: "/logos/alpha.png",
        t1_players: ["Ryan Smith", "Dodo Kong"],
        t2_name: "Team Beta",
        t2_score: 0,
        t2_logo: "/logos/beta.png",
        t2_players: ["Ethan Mahony", "Mary Layne Holloway"],
      },
    ],
    activeGameIndex: 1,
  },
  {
    match_id: "match_456",
    tournament_name: "Sunshine Slam",
    best_of: 5,
    rules: "First to 15 (win by 2)",
    winning: "Match tied 1–1",
    winner_team_id: null,
    games: [
      {
        number: 1,
        status: "final",
        t1_name: "Desert Smashers",
        t1_score: 13,
        t1_logo: "/logos/desert-smashers.png",
        t1_players: ["Avery Stone", "Luis Ortega"],
        t2_name: "Gulf Breeze",
        t2_score: 15,
        t2_logo: "/logos/gulf-breeze.png",
        t2_players: ["Parker Li", "Mila Santos"],
      },
      {
        number: 2,
        status: "final",
        t1_name: "Desert Smashers",
        t1_score: 15,
        t1_logo: "/logos/desert-smashers.png",
        t1_players: ["Avery Stone", "Luis Ortega"],
        t2_name: "Gulf Breeze",
        t2_score: 12,
        t2_logo: "/logos/gulf-breeze.png",
        t2_players: ["Parker Li", "Mila Santos"],
      },
      {
        number: 3,
        status: "in_progress",
        t1_name: "Desert Smashers",
        t1_score: 9,
        t1_logo: "/logos/desert-smashers.png",
        t1_players: ["Avery Stone", "Luis Ortega"],
        t2_name: "Gulf Breeze",
        t2_score: 11,
        t2_logo: "/logos/gulf-breeze.png",
        t2_players: ["Parker Li", "Mila Santos"],
      },
      {
        number: 4,
        status: "scheduled",
        t1_name: "Desert Smashers",
        t1_score: 0,
        t1_logo: "/logos/desert-smashers.png",
        t1_players: ["Avery Stone", "Luis Ortega"],
        t2_name: "Gulf Breeze",
        t2_score: 0,
        t2_logo: "/logos/gulf-breeze.png",
        t2_players: ["Parker Li", "Mila Santos"],
      },
      {
        number: 5,
        status: "scheduled",
        t1_name: "Desert Smashers",
        t1_score: 0,
        t1_logo: "/logos/desert-smashers.png",
        t1_players: ["Avery Stone", "Luis Ortega"],
        t2_name: "Gulf Breeze",
        t2_score: 0,
        t2_logo: "/logos/gulf-breeze.png",
        t2_players: ["Parker Li", "Mila Santos"],
      },
    ],
    activeGameIndex: 2,
  },
  {
    match_id: "match_789",
    tournament_name: "Pacific Open",
    best_of: 3,
    rules: "First to 11 (win by 2)",
    winning: "Wave Riders lead 2–0",
    winner_team_id: "wave_riders",
    games: [
      {
        number: 1,
        status: "final",
        t1_name: "Wave Riders",
        t1_score: 11,
        t1_logo: "/logos/wave-riders.png",
        t1_players: ["Kai Nakamura", "Sasha Ortiz"],
        t2_name: "Harbor Lights",
        t2_score: 9,
        t2_logo: "/logos/harbor-lights.png",
        t2_players: ["Emma Chen", "Zach Harper"],
      },
      {
        number: 2,
        status: "final",
        t1_name: "Wave Riders",
        t1_score: 11,
        t1_logo: "/logos/wave-riders.png",
        t1_players: ["Kai Nakamura", "Sasha Ortiz"],
        t2_name: "Harbor Lights",
        t2_score: 6,
        t2_logo: "/logos/harbor-lights.png",
        t2_players: ["Emma Chen", "Zach Harper"],
      },
      {
        number: 3,
        status: "scheduled",
        t1_name: "Wave Riders",
        t1_score: 0,
        t1_logo: "/logos/wave-riders.png",
        t1_players: ["Kai Nakamura", "Sasha Ortiz"],
        t2_name: "Harbor Lights",
        t2_score: 0,
        t2_logo: "/logos/harbor-lights.png",
        t2_players: ["Emma Chen", "Zach Harper"],
      },
    ],
    activeGameIndex: 2,
  },
];

const match_info = matches[0];

export const sampleMatches = matches;

export default match_info;
